# Generated by Django 4.2.3 on 2023-08-01 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="uploads/pdfs")),
                ("intro", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=20)),
                ("author_intro", models.CharField(max_length=200)),
                ("pickle", models.FileField(blank=True, upload_to="uploads/pickles")),
            ],
        ),
        migrations.CreateModel(
            name="Chats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book", models.CharField(max_length=50)),
                ("user_msg", models.CharField(max_length=400)),
                ("bot_msg", models.CharField(max_length=400)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
