# Generated by Django 4.2.3 on 2023-07-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="uploads/pdfs")),
                ("intro", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=20)),
                ("author_intro", models.CharField(max_length=200)),
            ],
        ),
    ]
