# Generated by Django 4.2.3 on 2023-08-30 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("book_cover", models.ImageField(upload_to="img")),
                ("file", models.FileField(upload_to="pdf")),
                ("intro", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=20)),
                ("author_intro", models.CharField(max_length=200)),
                ("pickle", models.FileField(blank=True, upload_to="pickle")),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msg", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_user_message", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookchat.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="users",
            field=models.ManyToManyField(
                related_name="users",
                through="bookchat.Chat",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
