# Generated by Django 4.1 on 2023-08-21 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_books_author_intro_remove_books_book_cover_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="author",
        ),
    ]
